### ISSUE TITLE
To interpolate or not when downscaling?

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/SW_Biomass#13]
For `project()` there are a variety of methods available.  The default, "bilinear" does bilinear interpolation.  There are other methods that smooth pixels differently. If we don't want to do interpolation, but just change the technical resolution so they can all be plotted together, "near" could be a good option.  Here's some examples with projecting the Liu dataset (0.25 resolution) to the ESA dataset (0.0008888889 resolution).

It's possible that we don't want to deal with figuring out what the "correct" method for interpolation is and we just use "near" for the purpose of aligning pixels across datasets for calculations.

Original:
![Screenshot 2024-02-08 at 11 30 13 AM](https://github.com/cct-datascience/SW_Biomass/assets/25404783/a538f9b8-ff20-4f72-b4ae-f0385e2fbd32)

method = "near"
![Screenshot 2024-02-08 at 11 29 47 AM](https://github.com/cct-datascience/SW_Biomass/assets/25404783/cce665d6-4b00-4409-82ce-56245bb5c4df)

method = "bilinear"
![Screenshot 2024-02-08 at 11 30 40 AM](https://github.com/cct-datascience/SW_Biomass/assets/25404783/2a2b7265-78e9-4f44-b752-3d6fa42b7610)

**Comment by CharlieDevine** [comment]
Eric and I discussed this earlier today, but I just wanted to formally comment here for the record. Because Liu AGB is estimated from inherently coarse passive microwave data, I think it's best to go with option 2 (nearest neighbor) to avoid interpolation of AGB values at ~1ha resolution since microwave can't resolve features at that scale.

**Comment by Aariq** [comment]
It also makes sense to use nearest neighbors for Liu et al. to match methods for the other coarse scale dataset, Menlove & Healey.  Menlove & Healey starts as a vector file of hexagons and just gets rasterized to the same resolution as the ESA product—it isn't clear how you would interpolate that data product from coarse hexagons to fine pixels.
